version: '3.8'

services:
  app:
    image: python:3.9-slim
    container_name: python_app
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null # Keep the container running for interaction
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - test_runner

  test_runner:
    image: python:3.9-slim
    container_name: test_runner
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
      pip install -r requirements.txt &&
      pytest --junitxml=results.xml"

